version: "3.8"

services:
  gotab-server:
    image: doxwant/gotab:latest
    container_name: gotab-server
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./sourceStore:/app/sourceStore
      - type: bind
    source: ./config.toml
    target: /app/config.toml
    environment:
      - SERVER_PORT=8080 # 环境变量
    restart: always # 推荐添加：容器退出时自动重启
    network_mode: host
